// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2jw8jRVD1A45GIvt3dyfVVgyQKlR8wM8',
    appId: '1:1018053508662:web:e1dd912c73cd601301a297',
    messagingSenderId: '1018053508662',
    projectId: 'myapp-ed1db',
    authDomain: 'myapp-ed1db.firebaseapp.com',
    storageBucket: 'myapp-ed1db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK83NgQ3hZv1-xCPLr3IffhKTwft9Mnmo',
    appId: '1:1018053508662:android:b686f2a951f67eeb01a297',
    messagingSenderId: '1018053508662',
    projectId: 'myapp-ed1db',
    storageBucket: 'myapp-ed1db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpB7G6cALN-UlPed9o9qiQStFWVkLUuoo',
    appId: '1:1018053508662:ios:cb49af22b3bf455601a297',
    messagingSenderId: '1018053508662',
    projectId: 'myapp-ed1db',
    storageBucket: 'myapp-ed1db.appspot.com',
    iosBundleId: 'com.example.myApp',
  );
}
